#include "../../common/num_config_vars.h"

#define EXAMPLE_ESP_WIFI_SSID      "Kite-Config"
#define EXAMPLE_ESP_WIFI_PASS      "password"
#define EXAMPLE_ESP_WIFI_CHANNEL   1
#define EXAMPLE_MAX_STA_CONN       1


static const char *TAG = "wifi softAP";
static void (*read_callback)(float*);
static void (*write_callback)(float*);
static void (*actuator_control_callback)(float, float, float, float, float, float, float);


Orientation_Data* orientation_data;

// ****** GET WEBSITE ******

static esp_err_t kite_config_html_handler(httpd_req_t *req)
{
	ESP_LOGI(TAG, "Getting html config page");
	
	esp_err_t error;
    const char* response = (const char*) req->user_ctx;
    error = httpd_resp_send(req, response, strlen(response));
    return error;
}

static const httpd_uri_t kite_config_get_html = {
    .uri       = "/config",
    .method    = HTTP_GET,
    .handler   = kite_config_html_handler,
    /* Let's pass response string in user
     * context to demonstrate it's usage */
    .user_ctx  = "	<!DOCTYPE html>\
<html>\
<head>\
					<style>\
					.button {\
					  border: none;\
					  color: white;\
					  padding: 15px 32px;\
					  text-align: center;\
					  text-decoration: none;\
					  display: inline-block;\
					  font-size: 16px;\
					  margin: 4px 2px;\
					  cursor: pointer;\
					}\
					\
					.button1 {background-color: #4CAF50;} /* Green */\
					\
					.slidecontainer {\
					  width: 100%;\
					}\
\
					.slider {\
					  -webkit-appearance: none;\
					  width: 100%;\
					  height: 25px;\
					  background: #d3d3d3;\
					  outline: none;\
					  opacity: 0.7;\
					  -webkit-transition: .2s;\
					  transition: opacity .2s;\
					}\
\
					.slider:hover {\
					  opacity: 1;\
					}\
\
					.slider::-webkit-slider-thumb {\
					  -webkit-appearance: none;\
					  appearance: none;\
					  width: 25px;\
					  height: 25px;\
					  background: #04AA6D;\
					  cursor: pointer;\
					}\
\
					.slider::-moz-range-thumb {\
					  width: 25px;\
					  height: 25px;\
					  background: #04AA6D;\
					  cursor: pointer;\
					}\
\
					tr td:last-child {\
						width: 1%;\
						white-space: nowrap;\
					}\
					tr td:first-child {\
						width: 1%;\
						white-space: nowrap;\
					}\n\
					</style>\n\
</head>\n\
<body>\n\
					\n\
					<canvas width = \"600\" height = \"400\" id = \"my_Canvas\"></canvas>\n\
					<button id=\"ResetConfig\" class=\"button button1\">&#8681</button>\n\
					<tr>\n\
							<td><p>Height=<br><span id=\"height_value\"></span></p></td>\n\
							<td><div class=\"slidecontainer\">\n\
								  <input type=\"range\" min=\"-200\" max=\"500\" value=\"0\" class=\"slider\" id=\"height_slider\">\n\
							</div></td>\n\
					</tr>\n\
					<tr>\n\
							<td><p>dH/dt =<br><span id=\"height_derivative_value\"></span></p></td>\n\
							<td><div class=\"slidecontainer\">\n\
								  <input type=\"range\" min=\"-200\" max=\"200\" value=\"0\" class=\"slider\" id=\"height_derivative_slider\">\n\
							</div></td>\n\
					</tr>\n\
					\n\
					<span id=\"autogeneratedHTML\"></span>\n\
					<label for=\"fname\">Save Configuration As: </label>\n\
					<input type=\"text\" id=\"filename\" name=\"filename\">\n\
					<button type=\"button\" id=\"saveButton\">Save</button><br><br>\n\
					Load configuration: <input type=\"file\" id=\"myfile\" name=\"myfile\"><br><br>\n\
					\n\
					\n\
					<script>\n\
						\n\
						function setHeight(height){\n\
							\n\
							window[\"height_value\"].innerHTML = height.toFixed(3);\n\
							window[\"height_slider\"].value = height*100;\n\
							\n\
						}\n\
						setHeight(3.3);\n\
						function setHeightDerivative(height_derivative){\n\
							\n\
							window[\"height_derivative_value\"].innerHTML = height_derivative.toFixed(3);\n\
							window[\"height_derivative_slider\"].value = height_derivative*100;\n\
							\n\
						}\n\
						setHeightDerivative(0);\n\
						\n\
						\n\
						function saveFile(filename, text){\n\
							var pom = document.createElement('a');\n\
							pom.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));\n\
							pom.setAttribute('download', filename);\n\
							\n\
							if(document.createEvent){\n\
								var event = document.createEvent('MouseEvents');\n\
								event.initEvent('click', true, true);\n\
								pom.dispatchEvent(event);\n\
							}else{\n\
								pom.click();\n\
							}\n\
						}\n\
						document.getElementById('saveButton').onclick = function(){\n\
							saveFile(\"\" + document.getElementById('filename').value + \".kiteconfig2\", JSON.stringify(configValues));\n\
						};\n\
						\n\
						document.getElementById('myfile').oninput = function(event){\n\
							let fileReader = new FileReader(); \n\
							fileReader.readAsText(document.getElementById('myfile').files[0]);\n\
							fileReader.onload = function() {\n\
								let result = JSON.parse(fileReader.result);\n\
								for (i = 7; i < Math.min(configValues.length, result.length); i++) {\n\
									configValues[i] = result[i];\n\
								}\n\
								updateConfigValuesInHTML();\n\
								uploadConfig();\n\
							}; \n\
							fileReader.onerror = function() {\n\
							  alert(fileReader.error);\n\
							};\n\
						};\n\
						\n\
						function downloadConfig(){\n\
							var xhr = new XMLHttpRequest();\n\
							xhr.open('GET', 'get_config', true);\n\
							xhr.responseType = 'text';\n\
							xhr.onload = function(e){\n\
								const myArray = xhr.response.split(\",\");\n\
								for(let i = 0; i < numConfigValues; i++){\n\
									configValues[i] = parseFloat(myArray[i]);\n\
								}\n\
								console.log(configValues);\n\
								updateConfigValuesInHTML();\n\
							}\n\
							xhr.send();\n\
						}\n\
						\n\
		  				var ready_to_download_orientation = true;\n\
						function downloadOrientation(){\n\
							var xhr = new XMLHttpRequest();\n\
							xhr.open('GET', 'getOrientation', true);\n\
							xhr.responseType = 'text';\n\
							xhr.onload = function(e){\n\
								const myArray = xhr.response.split(\",\");\n\
								for(let i = 0; i < 3; i++){\n\
									mov_matrix[i] = parseFloat(myArray[i]);\n\
									mov_matrix[4+i] = parseFloat(myArray[3+i]);\n\
									mov_matrix[8+i] = parseFloat(myArray[6+i]);\n\
								}\n\
								setHeight(parseFloat(myArray[12]));\n\
								setHeightDerivative(parseFloat(myArray[13]));\n\
		  						ready_to_download_orientation = true;\n\
								//console.log(mov_matrix);\n\
							}\n\
							xhr.send();\n\
						}\n\
						function uploadConfig(){\n\
							\n\
							let config_string = \"\";\n\
							for(let i = 0; i < numConfigValues-1; i++){\n\
								config_string += configValues[i] + \",\";\n\
							}\n\
							config_string += configValues[numConfigValues-1] + \",\";\n\
							sendData(config_string, 'uploadConfig',\n\
							() => {  console.log('succeeded sending config'); downloadConfig(); },\n\
							() => {  console.log('failed sending config'); downloadConfig(); }  );\n\
						}\n\
						\n\
						function controlActuators(elevonLeft, elevonRight, brake, rudder, propellerLeft, propellerRight){\n\
							\n\
							console.log(\"brake before sendData = \" + brake);\n\
							sendData(\"\" + elevonLeft + \",\" + elevonRight + \",\" + brake + \",\" + rudder + \",\" + propellerLeft + \",\" + propellerRight + \",\", 'uploadControls',\n\
							() => {  console.log('succeeded sending controls'); },\n\
							() => {  console.log('failed sending controls'); }  );\n\
						}\n\
						ready_to_upload_controls = true;\n\
						function sendData(data, filename, successCallback, failedCallback){\n\
							console.log(data);\n\
							var xmlhttp;\n\
							xmlhttp = new XMLHttpRequest();\n\
							xmlhttp.onreadystatechange = function() {\n\
								if (this.readyState == 4 && this.status != 200) {\n\
									failedCallback();\n\
									ready_to_upload_controls = true;\n\
								}\n\
								if(this.readyState == 4 && this.status == 200){\n\
									successCallback();\n\
									ready_to_upload_controls = true;\n\
								}\n\
							};\n\
							xmlhttp.open(\"POST\",filename,true);\n\
							xmlhttp.send(\"\" + data);\n\
						}\n\
						\n\
						\n\
						var numConfigValues = " NUM_CONFIG_FLOAT_VARS_string ";\n\
						var numActuatorsWithoutConfig = 2;\n\
						var configValues = new Array(numConfigValues).fill(0);\n\
						\n\
						var jsFunctions = new Array(numConfigValues + numActuatorsWithoutConfig);\n\
						\n\
						\n\
						\n\
						var UIstring = \"\";\n\
						\n\
						var need_to_upload_controls = false;\n\
						function uploadControls(){\n\
							console.log(\"window...innerHTML = \" + window[\"value\" + 10].innerHTML);\n\
							controlActuators(\n\
								  	window[\"value\" + 7].innerHTML,\n\
								  	window[\"value\" + 8].innerHTML,\n\
								  	window[\"value\" + 10].innerHTML,\n\
								  	window[\"value\" + 40].innerHTML,\n\
								  	window[\"value\" + (numConfigValues + 0)].innerHTML,\n\
								  	window[\"value\" + (numConfigValues + 1)].innerHTML\n\
								  );\n\
						}\n\
						\n\
						document.getElementById(\"ResetConfig\").onclick = function() {\n\
							for(let i = 0; i < 7; i++) configValues[i] = 0;\n\
							configValues[6] = 0.000024;\n\
							\n\
							configValues[7] = 1;\n\
							configValues[8] = 1;\n\
							configValues[9] = 0;\n\
							configValues[10] = 1;\n\
							configValues[11] = 0;\n\
							configValues[12] = 7;\n\
							configValues[13] = 90;\n\
							configValues[14] = 1;\n\
							configValues[15] = 1;\n\
							configValues[16] = 9;\n\
							configValues[17] = 1;\n\
							configValues[18] = 1;\n\
							configValues[19] = 1;\n\
							configValues[20] = 1;\n\
							configValues[21] = 1;\n\
							configValues[22] = 45;\n\
							configValues[23] = 1;\n\
							configValues[24] = 1;\n\
							configValues[25] = 1;\n\
							configValues[26] = 0.5;\n\
							configValues[27] = 1;\n\
							configValues[28] = 1;\n\
							configValues[29] = 1;\n\
							configValues[30] = 0;\n\
							configValues[31] = -9;\n\
							configValues[32] = 45;\n\
							configValues[33] = 0.9;\n\
							configValues[34] = 6;\n\
							configValues[35] = 0.85;\n\
							configValues[36] = 1;\n\
							configValues[37] = 0;\n\
							configValues[38] = 0;\n\
							configValues[39] = 0;\n\
							configValues[40] = 1;\n\
							configValues[41] = 0;\n\
							uploadConfig();\n\
						}\n\
						function addFixedConfig(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
							};\n\
						}\n\
						function addVariableConfig(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\n\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\n\
									<td></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								window[\"value\" + index].innerHTML = configValues[index];\n\
								\n\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\n\
									configValues[index] += 0.000001;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(0);\n\
									uploadConfig();\n\
								}\n\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\n\
									configValues[index] -= 0.000001;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(0);\n\
									uploadConfig();\n\
								}\n\
							};\n\
						}\n\
						function addServo(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><div class=\\\"slidecontainer\\\">\\\n\
								  		<input type=\\\"range\\\" min=\\\"-90\\\" max=\\\"90\\\" value=\\\"0\\\" class=\\\"slider\\\" id=\\\"slider\" + index + \"\\\">\\\n\
									</div></td>\\\
									<td><button id=\\\"invert\" + index + \"Button\\\" class=\\\"button button1\\\">Invert</button><button id=\\\"zero\" + index + \"Button\\\" class=\\\"button button1\\\">0</button></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"slider\" + index] = document.getElementById(\"slider\" + index);\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								window[\"value\" + index].innerHTML = window[\"slider\" + index].value;\n\
\n\
								window[\"slider\" + index].oninput = function() {\n\
								  window[\"value\" + index].innerHTML = this.value;\n\
								  need_to_upload_controls = true;\n\
								}\n\
								document.getElementById(\"invert\" + index + \"Button\").onclick = function() {\n\
									configValues[index] *= -1;\n\
									uploadConfig();\n\
								}\n\
								document.getElementById(\"zero\" + index + \"Button\").onclick = function() {\n\
									window[\"value\" + index].innerHTML = window[\"slider\" + index].value = 0;\n\
								  	need_to_upload_controls = true;\n\
								}\n\
							};\n\
						}\n\
						\n\
						function addPropeller(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><div class=\\\"slidecontainer\\\">\\\n\
								  		<input type=\\\"range\\\" min=\\\"0\\\" max=\\\"90\\\" value=\\\"0\\\" class=\\\"slider\\\" id=\\\"slider\" + index + \"\\\">\\\n\
									</div></td>\\\n\
									<td><button id=\\\"zero\" + index + \"Button\\\" class=\\\"button button1\\\">0</button></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"slider\" + index] = document.getElementById(\"slider\" + index);\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								window[\"value\" + index].innerHTML = window[\"slider\" + index].value;\n\
								\n\
								window[\"slider\" + index].oninput = function() {\n\
								  window[\"value\" + index].innerHTML = this.value;\n\
								  need_to_upload_controls = true;\n\
								}\n\
								\n\
								document.getElementById(\"zero\" + index + \"Button\").onclick = function() {\n\
									window[\"value\" + index].innerHTML = window[\"slider\" + index].value = 0;\n\
								  	need_to_upload_controls = true;\n\
								}\n\
							};\n\
						}\n\
						\n\
						function addSwitch(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td></td>\\\n\
									<td></td>\\\n\
									<td><button id=\\\"switch\" + index + \"Button\\\" class=\\\"button button1\\\">Switch \" + name + \"</button></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								\n\
								document.getElementById(\"switch\" + index + \"Button\").onclick = function() {\n\
									configValues[index] = (configValues[index] == 0) ? 1 : 0;\n\
									uploadConfig();\n\
								}\n\
							};\n\
						}\n\
						\n\
						function addPIDConstant(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\n\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\n\
									<td></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								//configValues[index] = 1;\n\
								window[\"value\" + index].innerHTML = configValues[index];\n\
								\n\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\n\
									configValues[index] *= 1.1;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(2);\n\
									uploadConfig();\n\
								}\n\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\n\
									configValues[index] /= 1.1;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(2);\n\
									uploadConfig();\n\
								}\n\
							};\n\
						}\n\
						\n\
						function addDegrees(name, index){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\n\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\n\
									<td></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								//configValues[index] = 45;\n\
								window[\"value\" + index].innerHTML = configValues[index];\n\
								\n\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\n\
									configValues[index] += 1;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(0);\n\
									uploadConfig();\n\
								}\n\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\n\
									configValues[index] -= 1;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(0);\n\
									uploadConfig();\n\
								}\n\
							};\n\
						}\n\
						\n\
						function addHeight(name, index, lowerBound){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\n\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\n\
									<td></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								//configValues[index] = 0.5;\n\
								window[\"value\" + index].innerHTML = configValues[index];\n\
								\n\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\n\
									configValues[index] += 0.5;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(1);\n\
									uploadConfig();\n\
								}\n\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\n\
									configValues[index] -= 0.5;\n\
									configValues[index] = Math.max(lowerBound, configValues[index]);\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(1);\n\
									uploadConfig();\n\
								}\n\
							};\n\
						}\n\
						\n\
						function addFraction(name, index, lowerBound){\n\
							UIstring += \"\\\n\
								<tr>\\\n\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\n\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\n\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\n\
									<td></td>\\\n\
								</tr>\\\n\
							\";\n\
							jsFunctions[index] = function(){\n\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\n\
								//configValues[index] = 0.5;\n\
								window[\"value\" + index].innerHTML = configValues[index];\n\
								\n\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\n\
									configValues[index] += 0.05;\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(1);\n\
									uploadConfig();\n\
								}\n\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\n\
									configValues[index] -= 0.05;\n\
									configValues[index] = Math.max(lowerBound, configValues[index]);\n\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(1);\n\
									uploadConfig();\n\
								}\n\
							};\n\
						}\n\
						\n\
						function updateConfigValuesInHTML(){\n\
							for(let i = 0; i < numConfigValues; i++){\n\
								if(document.getElementById(\"value\" + i) != null && i!=7 && i!=8 && i!=10 && i!=40 && i!= numConfigValues + 0 && i!=numConfigValues + 1){\n\
									document.getElementById(\"value\" + i).innerHTML = configValues[i];\n\
									console.log(document.getElementById(\"value\" + i));\n\
									console.log(configValues[i]);\n\
								}\n\
							}\n\
						}\n\
						\n\
						downloadConfig();\n\
						\n\
						let tableBegin = \"\\\n\
								<table style=\\\"width:100%\\\">\\\n\
								<tbody>\\n\
						\";\n\
						let tableEnd = \"\\\n\
								</tbody></table>\\\n\
						\";\n\
						\n\
						UIstring += \"<h3>Actuator Tests and Config</h3>\";\n\
						UIstring += tableBegin;\n\
								\n\
						addVariableConfig(\"BMP280 Calibration\", 6)\n\
						addServo(\"Brake\", 10);\n\
						addServo(\"Rudder\", 40);\n\
						addServo(\"Left Elevon\", 7);\n\
						addServo(\"Right Elevon\", 8);\n\
						addSwitch(\"Elevons\", 9);\n\
						addPropeller(\"Left Prop\", numConfigValues + 0);\n\
						addPropeller(\"Right Prop\", numConfigValues + 1);\n\
						addSwitch(\"Props\", 11);\n\
						addDegrees(\"Left Elevon Trim\", 37);\n\
						addDegrees(\"Right Elevon Trim\", 38);\n\
						addDegrees(\"Brake Trim\", 39);\n\
						addDegrees(\"Rudder Trim\", 41);\n\
						\n\
						UIstring += tableEnd;\n\
						UIstring += \"<h3>Eight Flying Config</h3>\";\n\
						UIstring += tableBegin;\n\
						\n\
						addHeight(\"Sideways Flying Time (s)\", 12, 0.5)\n\
						addHeight(\"Turning Speed (deg/s)\", 13, 0.5)\n\
						addPIDConstant(\"Eights Yaw(Z) Compensation(P)\", 27);\n\
						addPIDConstant(\"Eights Yaw(Z) Damping(D)\", 28);\n\
						addPIDConstant(\"Eights Pitch(Y) Damping\", 29);\n\
						addDegrees(\"Eights Elevator Offset (deg)\", 30);\n\
						addDegrees(\"Transition Pitch(Y) Angle (deg)\", 31);\n\
						addDegrees(\"Desired Line Angle from Horizon (deg)\", 32);\n\
						addPIDConstant(\"Beta Clamp\", 33);\n\
						addPIDConstant(\"Beta Compensation\", 34);\n\
						addFraction(\"Neutral Beta Fraction\", 35, 0.05);\n\
						\n\
						UIstring += tableEnd;\n\
						UIstring += \"<h3>Hover Launch Config</h3>\";\n\
						UIstring += tableBegin;\n\
						\n\
						addPIDConstant(\"Hover Pitch(Y) Compensation\", 14);\n\
						addPIDConstant(\"Hover Pitch(Y) Damping\", 15);\n\
						addDegrees(\"Pitch(Y) Offset\", 16)\n\
						addPIDConstant(\"Hover Yaw(Z) Compensation\", 17);\n\
						addPIDConstant(\"Hover Yaw(Z) Damping\", 18);\n\
						addPIDConstant(\"Hover Roll(X) Damping\", 19);\n\
						addPIDConstant(\"Hover Height Compensation\", 20);\n\
						addPIDConstant(\"Hover Height Dampening\", 21);\n\
						\n\
						UIstring += tableEnd;\n\
						UIstring += \"<h3>Landing Config</h3>\";\n\
						UIstring += tableBegin;\n\
						\n\
						addDegrees(\"Brake Angle (deg)\", 22)\n\
						addPIDConstant(\"Landing Pitch(Y) Compensation\", 23);\n\
						addPIDConstant(\"Landing Pitch(Y) Damping\", 24);\n\
						addPIDConstant(\"Landing Roll(X) Compensation\", 25);\n\
						addPIDConstant(\"Dive Angle Compensation\", 36);\n\
						addHeight(\"Landing Approach Height (m)\", 26, -100)\n\
						addFixedConfig(\"Accel x\", 0)\n\
						addFixedConfig(\"Accel y\", 1)\n\
						addFixedConfig(\"Accel z\", 2)\n\
						addFixedConfig(\"Gyro x\", 3)\n\
						addFixedConfig(\"Gyro y\", 4)\n\
						addFixedConfig(\"Gyro z\", 5)\n\
						\n\
						UIstring += tableEnd;\n\
						\n\
						document.getElementById(\"autogeneratedHTML\").innerHTML = UIstring;\n\
						\n\
						for(let i = 0; i < numConfigValues + numActuatorsWithoutConfig; i++){\n\
							if(typeof jsFunctions[i] === 'function'){\n\
								jsFunctions[i]();\n\
							}\n\
						}\n\
						\n\
						\n\
						\n\
						var canvas = document.getElementById('my_Canvas');\n\
         				gl = canvas.getContext('experimental-webgl');\n\
         				var vertices = [  -0.83600000,-3.79000000,-0.12400000,-0.83600000,-3.79000000,0.12400000,-0.83600000,3.79000000,-0.12400000,-0.83600000,3.79000000,0.12400000,0.83600000,-3.79000000,-0.12400000,0.83600000,-3.79000000,0.12400000,0.83600000,3.79000000,-0.12400000,0.83600000,3.79000000,0.12400000,-2.11215697,-9.0000000e-2,-1.59186587,-2.11215697,-9.0000000e-2,-9.9865868e-2,-2.11215697,9.0000000e-2,-1.59186587,-2.11215697,9.0000000e-2,-9.9865868e-2,-0.11215697,-9.0000000e-2,-1.59186587,-0.11215697,-9.0000000e-2,-9.9865868e-2,-0.11215697,9.0000000e-2,-1.59186587,-0.11215697,9.0000000e-2,-9.9865868e-2,1.03290445,-2.40582380,-1.4085955e-18,1.03290445,-2.36060825,0.22731396,1.03290445,-2.23184523,0.42002143,1.03290445,-2.03913776,0.54878444,1.03290445,-1.81182380,0.59400000,1.03290445,-1.58450984,0.54878444,1.03290445,-1.39180238,0.42002143,1.03290445,-1.26303936,0.22731396,1.03290445,-1.21782380,7.1335424e-17,1.03290445,-1.26303936,-0.22731396,1.03290445,-1.39180238,-0.42002143,1.03290445,-1.58450984,-0.54878444,1.03290445,-1.81182380,-0.59400000,1.03290445,-2.03913776,-0.54878444,1.03290445,-2.23184523,-0.42002143,1.03290445,-2.36060825,-0.22731396,0.87290445,-2.40582380,-1.4085955e-18,0.87290445,-2.36060825,0.22731396,0.87290445,-2.23184523,0.42002143,0.87290445,-2.03913776,0.54878444,0.87290445,-1.81182380,0.59400000,0.87290445,-1.58450984,0.54878444,0.87290445,-1.39180238,0.42002143,0.87290445,-1.26303936,0.22731396,0.87290445,-1.21782380,7.1335424e-17,0.87290445,-1.26303936,-0.22731396,0.87290445,-1.39180238,-0.42002143,0.87290445,-1.58450984,-0.54878444,0.87290445,-1.81182380,-0.59400000,0.87290445,-2.03913776,-0.54878444,0.87290445,-2.23184523,-0.42002143,0.87290445,-2.36060825,-0.22731396,1.03290445,1.30658751,-1.4085955e-18,1.03290445,1.35180306,0.22731396,1.03290445,1.48056608,0.42002143,1.03290445,1.67327355,0.54878444,1.03290445,1.90058751,0.59400000,1.03290445,2.12790146,0.54878444,1.03290445,2.32060893,0.42002143,1.03290445,2.44937195,0.22731396,1.03290445,2.49458751,7.1335424e-17,1.03290445,2.44937195,-0.22731396,1.03290445,2.32060893,-0.42002143,1.03290445,2.12790146,-0.54878444,1.03290445,1.90058751,-0.59400000,1.03290445,1.67327355,-0.54878444,1.03290445,1.48056608,-0.42002143,1.03290445,1.35180306,-0.22731396,0.87290445,1.30658751,-1.4085955e-18,0.87290445,1.35180306,0.22731396,0.87290445,1.48056608,0.42002143,0.87290445,1.67327355,0.54878444,0.87290445,1.90058751,0.59400000,0.87290445,2.12790146,0.54878444,0.87290445,2.32060893,0.42002143,0.87290445,2.44937195,0.22731396,0.87290445,2.49458751,7.1335424e-17,0.87290445,2.44937195,-0.22731396,0.87290445,2.32060893,-0.42002143,0.87290445,2.12790146,-0.54878444,0.87290445,1.90058751,-0.59400000,0.87290445,1.67327355,-0.54878444,0.87290445,1.48056608,-0.42002143,0.87290445,1.35180306,-0.22731396];\n\
\n\
        var colors = [        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	1.0, 1.0, 1.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0,        	0.0, 1.0, 0.0];\
\n\
         var indices = [ 1,5,2,2,3,1,2,5,6,2,8,4,3,5,1,3,8,7,4,3,2,4,8,3,5,8,6,6,8,2,7,5,3,7,8,5,9,13,10,10,11,9,10,13,14,10,16,12,11,13,9,11,16,15,12,11,10,12,16,11,13,16,14,14,16,10,15,13,11,15,16,13,17,25,18,17,33,32,18,24,19,18,33,17,18,35,34,19,23,20,19,35,18,20,22,21,20,35,19,20,37,36,21,37,20,22,20,23,22,37,21,22,39,38,23,19,24,23,39,22,24,18,25,24,39,23,24,41,40,25,17,26,25,41,24,26,32,27,26,41,25,26,43,42,27,31,28,27,43,26,28,30,29,28,43,27,28,45,44,29,45,28,30,28,31,30,45,29,30,47,46,31,27,32,31,47,30,32,26,17,32,33,48,32,47,31,33,41,48,34,33,18,34,40,33,35,39,34,36,35,20,36,38,35,37,38,36,38,37,22,39,35,38,40,34,39,40,39,24,41,33,40,42,41,26,42,48,41,43,47,42,44,43,28,44,46,43,45,46,44,46,45,30,47,43,46,48,42,47,48,47,32,49,57,50,49,65,64,50,56,51,50,65,49,50,67,66,51,55,52,51,67,50,52,54,53,52,67,51,52,69,68,53,69,52,54,52,55,54,69,53,54,71,70,55,51,56,55,71,54,56,50,57,56,71,55,56,73,72,57,49,58,57,73,56,58,64,59,58,73,57,58,75,74,59,63,60,59,75,58,60,62,61,60,75,59,60,77,76,61,77,60,62,60,63,62,77,61,62,79,78,63,59,64,63,79,62,64,58,49,64,65,80,64,79,63,65,73,80,66,65,50,66,72,65,67,71,66,68,67,52,68,70,67,69,70,68,70,69,54,71,67,70,72,66,71,72,71,56,73,65,72,74,73,58,74,80,73,75,79,74,76,75,60,76,78,75,77,78,76,78,77,62,79,75,78,80,74,79,80,79,64];\n\
\n\
		\n\
		for(let i = 0; i < vertices.length/3; i++){\n\
			vertices[i*3+1]*=-1;\n\
			vertices[i*3+2]*=-1;\n\
		}\n\
         var vertex_buffer = gl.createBuffer ();\n\
         gl.bindBuffer(gl.ARRAY_BUFFER, vertex_buffer);\n\
         gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(vertices), gl.STATIC_DRAW);\n\
			\n\
         var color_buffer = gl.createBuffer ();\n\
         gl.bindBuffer(gl.ARRAY_BUFFER, color_buffer);\n\
         gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(colors), gl.STATIC_DRAW);\n\
\n\
         var index_buffer = gl.createBuffer ();\n\
         gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, index_buffer);\n\
         \n\
         for(let i = 0; i < indices.length; i++){indices[i] -= 1;}\n\
         gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, new Uint16Array(indices), gl.STATIC_DRAW);\n\
\n\
         var vertCode = 'attribute vec3 position;'+\n\
            'uniform mat4 Pmatrix;'+\n\
            'uniform mat4 Vmatrix;'+\n\
            'uniform mat4 Mmatrix;'+\n\
            'attribute vec3 color;'+\n\
            'varying vec3 vColor;'+\n\
\n\
            'void main(void) { '+\n\
               'gl_Position = Pmatrix*Vmatrix*Mmatrix*vec4(position.x, position.y, position.z, 1.);'+\n\
               'vColor = color;'+\n\
            '}';\n\
\n\
         var fragCode = 'precision mediump float;'+\n\
            'varying vec3 vColor;'+\n\
            'void main(void) {'+\n\
               'gl_FragColor = vec4(vColor, 1.);'+\n\
            '}';\n\
\n\
         var vertShader = gl.createShader(gl.VERTEX_SHADER);\n\
         gl.shaderSource(vertShader, vertCode);\n\
         gl.compileShader(vertShader);\n\
\n\
         var fragShader = gl.createShader(gl.FRAGMENT_SHADER);\n\
         gl.shaderSource(fragShader, fragCode);\n\
         gl.compileShader(fragShader);\n\
\n\
         var shaderProgram = gl.createProgram();\n\
         gl.attachShader(shaderProgram, vertShader);\n\
         gl.attachShader(shaderProgram, fragShader);\n\
         gl.linkProgram(shaderProgram);\n\
\n\
         var Pmatrix = gl.getUniformLocation(shaderProgram, \"Pmatrix\");\n\
         var Vmatrix = gl.getUniformLocation(shaderProgram, \"Vmatrix\");\n\
         var Mmatrix = gl.getUniformLocation(shaderProgram, \"Mmatrix\");\n\
\n\
         gl.bindBuffer(gl.ARRAY_BUFFER, vertex_buffer);\n\
         var position = gl.getAttribLocation(shaderProgram, \"position\");\n\
         gl.vertexAttribPointer(position, 3, gl.FLOAT, false,0,0) ;\n\
         gl.enableVertexAttribArray(position);\n\
         gl.bindBuffer(gl.ARRAY_BUFFER, color_buffer);\n\
         var color = gl.getAttribLocation(shaderProgram, \"color\");\n\
         gl.vertexAttribPointer(color, 3, gl.FLOAT, false,0,0) ;\n\
\n\
         gl.enableVertexAttribArray(color);\n\
         gl.useProgram(shaderProgram);\n\
\n\
\n\
         function get_projection(angle, a, zMin, zMax) {\n\
            var ang = Math.tan((angle*.5)*Math.PI/180);\n\
            return [\n\
               0.5/ang, 0 , 0, 0,\n\
               0, 0.5*a/ang, 0, 0,\n\
               0, 0, -(zMax+zMin)/(zMax-zMin), -1,\n\
               0, 0, (-2*zMax*zMin)/(zMax-zMin), 0 \n\
            ];\n\
         }\n\
\n\
\n\
\n\
         function rotateZ(m, angle) {\n\
            var c = Math.cos(angle);\n\
            var s = Math.sin(angle);\n\
            var mv0 = m[0], mv4 = m[4], mv8 = m[8];\n\
\n\
            m[0] = c*m[0]-s*m[1];\n\
            m[4] = c*m[4]-s*m[5];\n\
            m[8] = c*m[8]-s*m[9];\n\
\n\
            m[1]=c*m[1]+s*mv0;\n\
            m[5]=c*m[5]+s*mv4;\n\
            m[9]=c*m[9]+s*mv8;\n\
         }\n\
\n\
         function rotateX(m, angle) {\n\
            var c = Math.cos(angle);\n\
            var s = Math.sin(angle);\n\
            var mv1 = m[1], mv5 = m[5], mv9 = m[9];\n\
\n\
            m[1] = m[1]*c-m[2]*s;\n\
            m[5] = m[5]*c-m[6]*s;\n\
            m[9] = m[9]*c-m[10]*s;\n\
\n\
            m[2] = m[2]*c+mv1*s;\n\
            m[6] = m[6]*c+mv5*s;\n\
            m[10] = m[10]*c+mv9*s;\n\
         }\n\
\n\
         function rotateY(m, angle) {\n\
            var c = Math.cos(angle);\n\
            var s = Math.sin(angle);\n\
            var mv0 = m[0], mv4 = m[4], mv8 = m[8];\n\
\n\
            m[0] = c*m[0]+s*m[2];\n\
            m[4] = c*m[4]+s*m[6];\n\
            m[8] = c*m[8]+s*m[10];\n\
\n\
            m[2] = c*m[2]-s*mv0;\n\
            m[6] = c*m[6]-s*mv4;\n\
            m[10] = c*m[10]-s*mv8;\n\
         }\n\
         \n\
         var proj_matrix = get_projection(40, canvas.width/canvas.height, 1, 100);\n\
\n\
         var mov_matrix = [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1];\n\
         var view_matrix = [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1];\n\
\n\
         view_matrix[14] = view_matrix[14]-6;\n\
\n\
         rotateZ(view_matrix, Math.PI*0.5);\n\
         rotateY(view_matrix, Math.PI);\n\
         //rotateX(view_matrix, Math.PI*0.5);\n\
\n\
         var time_old = 0;\n\
\n\
         var animate = function(time) {\n\
\n\
		  	if(ready_to_download_orientation){\n\
				downloadOrientation();\n\
		  		ready_to_download_orientation = false;\n\
		  	}\n\
		  	if(need_to_upload_controls && ready_to_upload_controls){\n\
		  		uploadControls();\n\
		  		need_to_upload_controls = false;\n\
		  		ready_to_upload_controls = false;\n\
		  	}\n\
            var dt = time-time_old;\n\
            time_old = time;\n\
\n\
            gl.enable(gl.DEPTH_TEST);\n\
            gl.depthFunc(gl.LEQUAL);\n\
            gl.clearColor(0.5, 0.5, 0.5, 0.9);\n\
            gl.clearDepth(1.0);\n\
\n\
            gl.viewport(0.0, 0.0, canvas.width, canvas.height);\n\
            gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);\n\
            gl.uniformMatrix4fv(Pmatrix, false, proj_matrix);\n\
            gl.uniformMatrix4fv(Vmatrix, false, view_matrix);\n\
            gl.uniformMatrix4fv(Mmatrix, false, mov_matrix);\n\
            gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, index_buffer);\n\
            gl.drawElements(gl.TRIANGLES, indices.length, gl.UNSIGNED_SHORT, 0);\n\
\n\
            setTimeout(() => {  window.requestAnimationFrame(animate); }, 100);\n\
         }\n\
         animate(0);\n\
					</script>\n\
</body>\n\
</html>"
};

// ****** GET CONFIG ******
static char response2[1000];
float float_values[NUM_CONFIG_FLOAT_VARS];
static esp_err_t config_get_handler(httpd_req_t *req)
{
	ESP_LOGI(TAG, "Getting config values");
	esp_err_t error;
	
    (*read_callback)(float_values);
    
	//char response2[NUM_CONFIG_FLOAT_VARS*20];
    sprintf(response2, "%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f", 
    	float_values[0],
    	float_values[1],
    	float_values[2],
    	float_values[3],
    	float_values[4],
    	float_values[5],
    	float_values[6],
    	float_values[7],
    	float_values[8],
    	float_values[9],
    	float_values[10],
    	float_values[11],
    	float_values[12],
    	float_values[13],
    	float_values[14],
    	float_values[15],
    	float_values[16],
    	float_values[17],
    	float_values[18],
    	float_values[19],
    	float_values[20],
    	float_values[21],
    	float_values[22],
    	float_values[23],
    	float_values[24],
    	float_values[25],
    	float_values[26],
    	float_values[27],
    	float_values[28],
    	float_values[29],
    	float_values[30],
    	float_values[31],
    	float_values[32],
    	float_values[33],
    	float_values[34],
    	float_values[35],
    	float_values[36],
    	float_values[37],
    	float_values[38],
    	float_values[39],
    	float_values[40],
    	float_values[41]
    );
    
    error = httpd_resp_send(req, response2, strlen(response2));
    return error;
}

static const httpd_uri_t kite_config_get_values = {
    .uri       = "/get_config",
    .method    = HTTP_GET,
    .handler   = config_get_handler,
    /* Let's pass response string in user
     * context to demonstrate it's usage */
    .user_ctx  = NULL
};

// ****** GET ORIENTATION DATA ******

static esp_err_t orientation_get_handler(httpd_req_t *req)
{
	ESP_LOGI(TAG, "Getting kite orientation");
	esp_err_t error;
    
    sprintf(response2, "%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f", orientation_data->rotation_matrix[0], orientation_data->rotation_matrix[3], orientation_data->rotation_matrix[6],
    orientation_data->rotation_matrix[1], orientation_data->rotation_matrix[4], orientation_data->rotation_matrix[7],
    orientation_data->rotation_matrix[2], orientation_data->rotation_matrix[5], orientation_data->rotation_matrix[8],
    orientation_data->gyro_in_kite_coords[0], orientation_data->gyro_in_kite_coords[1], orientation_data->gyro_in_kite_coords[2],
    getHeight(), getHeightDerivative());
    
    error = httpd_resp_send(req, response2, strlen(response2));
    return error;
}

static const httpd_uri_t kite_orientation_get_values = {
    .uri       = "/getOrientation",
    .method    = HTTP_GET,
    .handler   = orientation_get_handler,
    /* Let's pass response string in user
     * context to demonstrate it's usage */
    .user_ctx  = NULL
};

int getIndexToNextNumber(char* string_arg, int current_index){
	while(string_arg[current_index] != 44){
    	current_index++;
    }
    current_index++;
    return current_index;
}

// ****** POST CONFIG ******

esp_err_t config_post_handler(httpd_req_t *req)
{
	ESP_LOGI(TAG, "Posting config to kite");
    char content[NUM_CONFIG_FLOAT_VARS*20];

    size_t recv_size = MIN(req->content_len, sizeof(content));

    int ret = httpd_req_recv(req, content, recv_size);
    
    if (ret <= 0) return ESP_FAIL;
    
    int string_position = 0;
    float config_float_values[NUM_CONFIG_FLOAT_VARS];
    for(int i = 0; i < NUM_CONFIG_FLOAT_VARS; i++){
    	config_float_values[i] = atof(content+string_position);
    	string_position = getIndexToNextNumber(content, string_position);
    }
	
	(*write_callback)(config_float_values);
	
    /* Send a simple response */
    const char resp[] = "URI POST Response";
    httpd_resp_send(req, resp, HTTPD_RESP_USE_STRLEN);
    return ESP_OK;
}

/* URI handler structure for POST /uri */
httpd_uri_t config_post = {
    .uri      = "/uploadConfig",
    .method   = HTTP_POST,
    .handler  = config_post_handler,
    .user_ctx = NULL
};

// ****** POST ACTUATOR CONTROLS ******


char content[20]; // 3(length of number, e.g. "-90") * 5 + 4(commata)
esp_err_t control_post_handler(httpd_req_t *req)
{
	ESP_LOGI(TAG, "Posting controls to kite");
    

    size_t recv_size = MIN(req->content_len, sizeof(content));

    int ret = httpd_req_recv(req, content, recv_size);
    
    if (ret <= 0) return ESP_FAIL;
    
    int string_position = 0;
    float controls[6];
    for(int i = 0; i < 6; i++){
    	controls[i] = atof(content+string_position);
    	string_position = getIndexToNextNumber(content, string_position);
    }
    printf("controls[0...5] = %f, %f, %f, %f, %f, %f\n", controls[0], controls[1], controls[2], controls[3], controls[4], controls[5]);
    
	(*actuator_control_callback)(controls[0], controls[1], controls[2], controls[3], controls[4], controls[5], 50);
	
	
    /* Send a simple response */
    const char resp[] = "URI POST Response";
    httpd_resp_send(req, resp, HTTPD_RESP_USE_STRLEN);
    return ESP_OK;
}

/* URI handler structure for POST /uri */
httpd_uri_t control_post = {
    .uri      = "/uploadControls",
    .method   = HTTP_POST,
    .handler  = control_post_handler,
    .user_ctx = NULL
};



/* This handler allows the custom error handling functionality to be
 * tested from client side. For that, when a PUT request 0 is sent to
 * URI /ctrl, the /hello and /echo URIs are unregistered and following
 * custom error handler http_404_error_handler() is registered.
 * Afterwards, when /hello or /echo is requested, this custom error
 * handler is invoked which, after sending an error message to client,
 * either closes the underlying socket (when requested URI is /echo)
 * or keeps it open (when requested URI is /hello). This allows the
 * client to infer if the custom error handler is functioning as expected
 * by observing the socket state.
 */
esp_err_t http_404_error_handler(httpd_req_t *req, httpd_err_code_t err)
{
    /* For any other URI send 404 and close socket */
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Some 404 error message");
    return ESP_FAIL;
}

static httpd_handle_t start_webserver(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.lru_purge_enable = true;

    // Start the httpd server
    ESP_LOGI(TAG, "Starting server on port: '%d'", config.server_port);
    if (httpd_start(&server, &config) == ESP_OK) {
        // Set URI handlers
        ESP_LOGI(TAG, "Registering URI handlers");
        httpd_register_uri_handler(server, &kite_config_get_html);
        httpd_register_uri_handler(server, &kite_config_get_values);
        httpd_register_uri_handler(server, &kite_orientation_get_values);
        httpd_register_uri_handler(server, &config_post);
        httpd_register_uri_handler(server, &control_post);
        #if CONFIG_EXAMPLE_BASIC_AUTH
        httpd_register_basic_auth(server);
        #endif
        return server;
    }

    ESP_LOGI(TAG, "Error starting server!");
    return NULL;
}

static void stop_webserver(httpd_handle_t server)
{
    // Stop the httpd server
    httpd_stop(server);
}

static void disconnect_handler(void* arg, esp_event_base_t event_base,
                               int32_t event_id, void* event_data)
{
    httpd_handle_t* server = (httpd_handle_t*) arg;
    if (*server) {
        ESP_LOGI(TAG, "Stopping webserver");
        stop_webserver(*server);
        *server = NULL;
    }
}

static void connect_handler(void* arg, esp_event_base_t event_base,
                            int32_t event_id, void* event_data)
{
    httpd_handle_t* server = (httpd_handle_t*) arg;
    if (*server == NULL) {
        ESP_LOGI(TAG, "Starting webserver");
        *server = start_webserver();
    }
}

// ACCESS POINT FUNCTIONALITY

static void wifi_event_handler(void* arg, esp_event_base_t event_base,
                                    int32_t event_id, void* event_data)
{
    if (event_id == WIFI_EVENT_AP_STACONNECTED) {
        wifi_event_ap_staconnected_t* event = (wifi_event_ap_staconnected_t*) event_data;
        ESP_LOGI(TAG, "station "MACSTR" join, AID=%d",
                 MAC2STR(event->mac), event->aid);
    } else if (event_id == WIFI_EVENT_AP_STADISCONNECTED) {
        wifi_event_ap_stadisconnected_t* event = (wifi_event_ap_stadisconnected_t*) event_data;
        ESP_LOGI(TAG, "station "MACSTR" leave, AID=%d",
                 MAC2STR(event->mac), event->aid);
    }
}

void wifi_init_softap(void)
{
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_create_default_wifi_ap();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
                                                        ESP_EVENT_ANY_ID,
                                                        &wifi_event_handler,
                                                        NULL,
                                                        NULL));

    wifi_config_t wifi_config = {
        .ap = {
            .ssid = EXAMPLE_ESP_WIFI_SSID,
            .ssid_len = strlen(EXAMPLE_ESP_WIFI_SSID),
            .channel = EXAMPLE_ESP_WIFI_CHANNEL,
            .password = EXAMPLE_ESP_WIFI_PASS,
            .max_connection = EXAMPLE_MAX_STA_CONN,
            .authmode = WIFI_AUTH_WPA_WPA2_PSK
        },
    };
    if (strlen(EXAMPLE_ESP_WIFI_PASS) == 0) {
        wifi_config.ap.authmode = WIFI_AUTH_OPEN;
    }

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_LOGI(TAG, "wifi_init_softap finished. SSID:%s password:%s channel:%d",
             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS, EXAMPLE_ESP_WIFI_CHANNEL);
}

// init wifi on the esp
// register callbacks
void network_setup_configuring(void (*read_callback_arg)(float*), void (*write_callback_arg)(float*), void (*actuator_control_callback_arg)(float, float, float, float, float, float, float), Orientation_Data* orientation_data_arg)
{
	orientation_data = orientation_data_arg;
	read_callback = read_callback_arg;
	write_callback = write_callback_arg;
	actuator_control_callback = actuator_control_callback_arg;
	static httpd_handle_t server = NULL;
	
    //Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);
    ESP_LOGI(TAG, "ESP_WIFI_MODE_AP");
    wifi_init_softap();
    
    
    ESP_ERROR_CHECK(esp_netif_init());
    
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, &connect_handler, &server));
    //ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_DISCONNECTED, &disconnect_handler, &server));
    
}
